package com.ideaknow.api.client.model.informational;

import android.os.Parcel;
import android.os.Parcelable;

import java.util.ArrayList;

public class InformationalModel implements Parcelable {

    private ArrayList<CatalogModel> catalog;
    private String publishDate;
    private ArrayList<AppsModel> apps;
    private String version;
    private String ttl; //Time To Live. This is generated by API to know if cached data is still valid.
    private String language; //Language of cached data (Spanish, English...)

    public ArrayList<CatalogModel> getCatalog() {
        return catalog;
    }

    public void setCatalog(ArrayList<CatalogModel> catalog) {
        this.catalog = catalog;
    }

    public String getPublishDate() {
        return publishDate;
    }

    public void setPublishDate(String publishDate) {
        this.publishDate = publishDate;
    }

    public ArrayList<AppsModel> getApps() {
        return apps;
    }

    public void setApps(ArrayList<AppsModel> apps) {
        this.apps = apps;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getTtl() {
        return ttl;
    }

    public void setTtl(String ttl) {
        this.ttl = ttl;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeTypedList(catalog);
        dest.writeString(this.publishDate);
        dest.writeTypedList(apps);
        dest.writeString(this.version);
        dest.writeString(this.ttl);
        dest.writeString(this.language);
    }

    public InformationalModel() {
    }

    protected InformationalModel(Parcel in) {
        this.catalog = in.createTypedArrayList(CatalogModel.CREATOR);
        this.publishDate = in.readString();
        this.apps = in.createTypedArrayList(AppsModel.CREATOR);
        this.version = in.readString();
        this.ttl = in.readString();
        this.language = in.readString();
    }

    public static final Parcelable.Creator<InformationalModel> CREATOR = new Parcelable.Creator<InformationalModel>() {
        @Override
        public InformationalModel createFromParcel(Parcel source) {
            return new InformationalModel(source);
        }

        @Override
        public InformationalModel[] newArray(int size) {
            return new InformationalModel[size];
        }
    };
}
